import {
  Achievement,
  Company,
  Project,
  Skill,
  SocialLink,
} from "@/types/portfolio";
import { findCompanyByAlias, getTechStack } from "@/utils/portfolio";

export const SocialLinks: SocialLink[] = [
  {
    href: "#",
    name: "whatsapp",
    icon: "logos:whatsapp-icon",
    text: "(+91)-7984452648",
    visible: true,
  },
  {
    href: "https://www.linkedin.com/in/pathakaman7/",
    name: "linkedin",
    icon: "logos:linkedin-icon",
    text: "pathakaman",
    visible: true,
  },
  {
    href: "https://github.com/DevPathakam/",
    name: "github",
    icon: "uil:github",
    text: "DevPathakam",
    visible: true,
  },
];

export const CategoryValues = [
  "libraries",
  "frameworks",
  "frontend",
  "backend",
  "languages",
  "database",
  "tools",
  "devops",
  "mobile",
  "others",
  "stylesheets",
  "animation",
] as const;

export const Skills: Skill[] = [
  {
    name: "React",
    alias: "react",
    icon: "devicon:react",
    visible: true,
    isFeatured: true,
    category: [
      "libraries",
      "frontend"
    ],
    tags: ["React.js"],
  },
  {
    name: "Javascript",
    alias: "js",
    icon: "devicon:javascript",
    visible: true,
    isFeatured: true,
    category: ["languages", "frontend"],
    tags: ["ES6+"],
  },
  {
    name: "Next JS",
    alias: "next",
    icon: "devicon:nextjs",
    visible: true,
    category: ["frameworks", "backend", "frontend"],
  },
  {
    name: "Typescript",
    alias: "ts",
    icon: "devicon:typescript",
    visible: true,
    isFeatured: true,
    category: ["languages", "backend", "frontend"],
  },
  {
    name: "React Native (Expo)",
    alias: "expo",
    icon: "material-icon-theme:expo",
    visible: true,
    isFeatured: true,
    category: ["frameworks", "mobile"],
  },
  {
    name: "Redux",
    alias: "redux",
    icon: "devicon:redux",
    visible: true,
    isFeatured: true,
    category: ["libraries", "frontend"],
    tags: ["state management"]
  },
  {
    name: "Redux Saga",
    alias: "redux_saga",
    icon: "simple-icons:reduxsaga",
    visible: true,
    isFeatured: true,
    category: ["libraries", "frontend"],
    tags: ["state management"]
  },
  // {
  //   name: "Zustand",
  //   alias: "zustand",
  //   icon: "devicon:zustand",
  //   visible: true,
  //   isFeatured: true,
  //   category: ["libraries", "frontend"],
  //   tags: ["state management"]
  // },
  {
    name: "React Flow",
    alias: "flow",
    icon: "fluent:flow-16-regular",
    visible: true,
    category: ["libraries", "frontend"],
  },
  {
    name: "Bootstrap",
    alias: "bootstrap",
    icon: "devicon:bootstrap",
    visible: true,
    isFeatured: true,
    category: ["frameworks", "frontend", "stylesheets"],
  },
  {
    name: "Tailwind CSS",
    alias: "tailwind",
    icon: "devicon:tailwindcss",
    visible: true,
    category: ["frameworks", "frontend", "stylesheets"],
  },
  {
    name: "Motion",
    alias: "motion",
    icon: "devicon:motion",
    visible: false,
    isFeatured: false,
    category: ["libraries", "frontend", "animation"],
  },
  // {
  //   name: "GSAP",
  //   alias: "gsap",
  //   icon: "simple-icons:gsap",
  //   visible: false,
  //   isFeatured: false,
  //   category: ["libraries", "frontend", "animation"],
  // },
  // {
  //   name: "Three JS",
  //   alias: "three",
  //   icon: "skill-icons:threejs-dark",
  //   visible: false,
  //   isFeatured: false,
  //   category: ["libraries", "frontend", "animation"],
  //   tags: ["3D"]
  // },
  // {
  //   name: "CUDA Programming",
  //   alias: "cuda",
  //   icon: "material-icon-theme:cuda",
  //   visible: false,
  //   isFeatured: false,
  //   category: ["languages", "backend"],
  // },
  {
    name: "NodeJS",
    alias: "node",
    icon: "vscode-icons:file-type-node",
    visible: true,
    isFeatured: true,
    category: ["libraries", "backend"],
  },
  {
    name: "ExpressJS",
    alias: "express",
    icon: "simple-icons:express",
    visible: true,
    isFeatured: false,
    category: ["libraries", "backend"],
  },
  {
    name: "Angular JS",
    alias: "angularjs",
    icon: "devicon:angularjs",
    visible: true,
    category: ["libraries", "frontend"],
  },
  {
    name: "Angular",
    alias: "angular",
    icon: "devicon:angular",
    visible: true,
    category: ["frameworks", "frontend"],
  },
  {
    name: "Python",
    alias: "python",
    icon: "devicon:python",
    visible: true,
    isFeatured: true,
    category: ["languages", "backend"],
  },
  {
    name: "SQL",
    alias: "sql",
    icon: "vscode-icons:file-type-sql",
    visible: true,
    category: ["database", "backend"],
  },
  {
    name: "MongoDB",
    alias: "mongo",
    icon: "devicon:mongodb",
    visible: true,
    category: ["database", "backend"],
  },
  {
    name: "HTML",
    alias: "html",
    icon: "skill-icons:html",
    visible: true,
    category: ["languages", "frontend"],
  },
  {
    name: "CSS",
    alias: "css",
    icon: "devicon:css",
    visible: true,
    category: ["frontend", "stylesheets"],
  },
  {
    name: "SCSS",
    alias: "scss",
    icon: "devicon:sass",
    visible: false,
    category: ["frontend", "stylesheets"],
  },
  {
    name: "Apache Airflow",
    alias: "airflow",
    icon: "devicon:apacheairflow",
    visible: true,
    isFeatured: false,
    category: ["tools", "backend", "devops"],
  },
  {
    name: "Docker",
    alias: "docker",
    icon: "devicon:docker",
    visible: true,
    isFeatured: false,
    category: ["tools", "devops"],
  },
  {
    name: "Github Actions",
    alias: "github_actions",
    icon: "devicon:githubactions",
    visible: true,
    isFeatured: false,
    category: ["tools", "devops"],
    tags: ["CI/CD"]
  },
  {
    name: "Git",
    alias: "git",
    icon: "devicon:git",
    visible: true,
    isFeatured: true,
    category: ["tools"],
  },
  {
    name: "Github",
    alias: "github",
    icon: "mdi:github",
    visible: true,
    category: ["tools"],
  },
  {
    name: "JIRA",
    alias: "jira",
    icon: "devicon:jira",
    visible: true,
    isFeatured: false,
    category: ["tools"],
  },
  {
    name: "LM Studio",
    alias: "lm",
    icon: "simple-icons:lmstudio",
    visible: true,
    isFeatured: true,
    category: ["tools", "backend"],
  },
  {
    name: "Ollama",
    alias: "ollama",
    icon: "selfhst:ollama-light",
    visible: true,
    category: ["tools"],
  },
  {
    name: "Cursor",
    alias: "cursor",
    icon: "devicon-plain:cursor",
    visible: true,
    category: ["tools"],
  },
  {
    name: "ESLint",
    alias: "eslint",
    icon: "devicon:eslint",
    visible: true,
    category: ["tools"],
  },
  {
    name: "Prettier",
    alias: "prettier",
    icon: "material-icon-theme:prettier",
    visible: true,
    category: ["tools"],
  },
  {
    name: "Agile Methodologies",
    alias: "agile",
    icon: "iconoir:agile",
    visible: true,
    isFeatured: false,
    category: ["others"],
  },
  {
    name: "Kanban Methodologies",
    alias: "kanban",
    icon: "bi:kanban",
    visible: true,
    category: ["others"],
  },
  {
    name: "Responsive Web Design",
    alias: "responsiveness",
    icon: "mdi:responsive",
    visible: true,
    isFeatured: true,
    category: ["others"],
  },
  {
    name: "REST API",
    alias: "rest",
    icon: "dashicons:rest-api",
    visible: true,
    isFeatured: false,
    category: ["others"],
  },
  {
    name: "Prompt Engineering",
    alias: "prompting",
    icon: "material-icon-theme:prompt",
    visible: true,
    isFeatured: false,
    category: ["others"],
  },
];

export const SkillSchema = [
  "name",
  "category",
  "tags",
] as const;

export const Companies: Company[] = [
  {
    name: "RedSoft Solutions Pvt. Ltd.",
    alias: "redsoft",
    roles: ["Software Developer"],
    location: "Surat",
    workFrom: { month: "Feb", year: 2017 },
    workTo: { month: "Apr", year: 2018 },
    isCurrent: false,
    jobType: "Full-Time",
    workMode: "In-Office",
  },
  {
    name: "WebOsmotic",
    alias: "wo",
    roles: ["Jr. Software Developer"],
    location: "Surat",
    workFrom: { month: "May", year: 2018 },
    workTo: { month: "Jul", year: 2020 },
    isCurrent: false,
    jobType: "Full-Time",
    workMode: "In-Office",
  },
  {
    name: "Shukul Infotech Pvt. Ltd.",
    alias: "shukul",
    roles: ["Software Developer"],
    location: "Surat",
    workFrom: { month: "Aug", year: 2020 },
    workTo: { month: "Dec", year: 2020 },
    isCurrent: false,
    jobType: "Full-Time",
    workMode: "In-Office",
  },
  {
    name: "LogicalWings Infoweb Pvt. Ltd.",
    alias: "lw",
    roles: ["Sr. frontend Developer", "frontend Developer"],
    location: "Vadodara",
    workFrom: { month: "Feb", year: 2021 },
    isCurrent: true,
    jobType: "Full-Time",
    workMode: "Remote",
  },
];

export const Projects: Project[] = [
  {
    name: "Templato",
    alias: "templato",
    highlight: 'A dynamic form generation platform that let user select fields and custom components and create a complex form template to be distributed.',
    points: ["Point 1", "Point 2"],
    company: findCompanyByAlias("redsoft"),
    isPersonal: false,
    techStack: getTechStack(["angularjs", "js", "html", "css", "bootstrap"]),
    duration: '10 months',
    isVisible: true,
  },
  {
    name: "MovieRanker",
    alias: "movie_ranker",
    highlight: "MovieRanker is a dynamic, database-driven platform designed for film enthusiasts to discover, track, and rank cinema through a real-time community engagement algorithm. The application features responsive UI components and interactive dashboards, offering a scalable solution for managing streaming and theater releases.",
    points: ["Point 1", "Point 2"],
    company: findCompanyByAlias("wo"),
    isPersonal: false,
    techStack: getTechStack(["angular", "js", "html", "css", "bootstrap"]),
    duration: '5 months',
    liveUrl: "https://www.movieranker.com/",
    isVisible: true,
  },
  {
    name: "ParcelPort",
    alias: "parcel_port",
    highlight: "An innovative corporate web solution designed to showcase B2B smart locker technology across residential, commercial, and retail logistics sectors. Built as a high-density operational portal, it details secure hardware infrastructure, responsive API integrations for courier-agnostic drop-offs, and strategic workflow solutions for retail returns and BOPIS (Buy Online, Pick Up In Store) logistics.",
    points: ["Point 1", "Point 2"],
    company: findCompanyByAlias("wo"),
    isPersonal: false,
    techStack: getTechStack([
      "angular",
      "js",
      "ts",
      "html",
      "css",
      "bootstrap",
      "node",
      "express",
    ]),
    duration: '1.5 years',
    isVisible: true,
  },
  {
    name: "ItsKeedi",
    alias: "its_keedi",
    highlight: "Itskeedi is brainchild to promote local business. It empowers vendors and its customer to transact with more benefits passed-on to them. It is a unique platform to enable local sellers to reach out to buyers with the best offers and services. With this platform we hope to strengthen local trade with buyers can buy the best available products locally. This e-commerce model can transform local trade practices with digital adoption.",
    points: ["Point 1", "Point 2"],
    company: findCompanyByAlias("shukul"),
    isPersonal: false,
    techStack: getTechStack([
      "angular",
      "js",
      "html",
      "css",
      "bootstrap",
      "node",
      "express",
    ]),
    duration: '4 months',
    isVisible: true,
  },
  {
    name: "WingsTrack",
    alias: "wings_track",
    highlight: "Wings Track is a real-time family safety and geolocation mobile application designed to securely connect family circles through advanced tracking logistics. The platform leverages GPS tracking technology to deliver live location mapping, precise seven-day historical route timelines, and instant geofencing alerts for customized safe zones.",
    points: ["Point 1", "Point 2"],
    company: findCompanyByAlias("lw"),
    isPersonal: false,
    techStack: getTechStack([
      "angular",
      "js",
      "bootstrap",
      "node",
      "express",
      "sql",
    ]),
    duration: '1 year',
    isVisible: false,
  },
  {
    name: "Levrx",
    alias: "levrx",
    highlight: "Levrx is the industry-leading pharmacy hub connecting every player in the pharmacy ecosystem. Levrx unifies pharmacy, benefit, and clinical data into a single digital experience, giving providers and patients clear answers on what it will cost, where to go, and what to do next before a prescription is filled. By turning complexity into real-time, actionable guidance in one place, Levrx reduces friction, captures savings that would otherwise be missed, and improves outcomes across the entire healthcare experience.",
    points: ["Scaled and optimized a comprehensive digital healthcare and pharmacy savings platform (Levrx), driving development across two React web applications (Member and Admin portals) and a React Native Expo mobile application.", "Audited and overhauled frontend applications to drastically elevate core performance metrics, successfully reducing Largest Contentful Paint (LCP), First Contentful Paint (FCP), and Cumulative Layout Shift (CLS)", "Actively led rigorous code reviews and engineering initiatives that successfully elevated application scores to 90% for Accessibility and 90% for Development Best Practices."],
    company: findCompanyByAlias("lw"),
    isPersonal: false,
    techStack: getTechStack(["react", "expo", "js", "ts", "bootstrap", "redux"]),
    duration: '5 years',
    liveUrl: "https://mwa.levrx.com/cdphp/login",
    isVisible: true,
  },
  {
    name: "SysGenie",
    alias: "sys_genie",
    points: ["Point 1", "Point 2"],
    isPersonal: true,
    techStack: getTechStack([
      "react",
      "flow",
      "tailwind",
      "node",
      "express",
      "lm",
    ]),
    duration: '3 weeks',
    isVisible: true,
  },
  {
    name: "Personal Branding Site",
    alias: "personal_site",
    points: ["Point 1", "Point 2"],
    isPersonal: true,
    techStack: getTechStack(["react", "next", "tailwind"]),
    duration: '1 week',
    isVisible: true,
  },
];

export const Achievements: Achievement[] = [
  {
    name: "Technocrat of the year",
    type: "award",
    year: 2021,
    achievedAt: findCompanyByAlias("lw"),
  },
  {
    name: "Team of the year",
    type: "award",
    year: 2023,
    achievedAt: findCompanyByAlias("lw"),
  },
  {
    name: "Agile Scrum Master Completion Certification",
    type: "certification",
    year: 2024,
    achievedFrom: "Simplilearn",
  },
  {
    name: "Employee of the year",
    type: "award",
    year: 2025,
    achievedAt: findCompanyByAlias("lw"),
  },
];

export const ScrollbarClasses =
  "[&::-webkit-scrollbar]:h-0.75 [&::-webkit-scrollbar-track]:bg-brand-primary  [&::-webkit-scrollbar-thumb]:bg-brand-primary-highlight hover:[&::-webkit-scrollbar-thumb]:bg-brand-primary-highlight active:[&::-webkit-scrollbar-thumb]:bg-brand-primary-highlight";
